[package]
name = "jason-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
jason-rs = "0.3.2"
serde_json = "1.0"

#needed for windows 
mlua = { version = "0.10", default-features = false, features = ["serialize", "vendored", "luajit"] }
